### PR TITLE
Updated PO's

### PR DESCRIPTION
**Pull request by JVickery-TBS**
feat(i18n): extracted messages and updated catalogs;

- Extracted messages to POT.
- Updated en and fr POs.

### CODE REVIEW

**Comment by wardi** [comment]
this one will be tricky because it's pretty technical, only users adding a custom json schema will see these messages and this is a fork of an old version for python 2 compatibility that won't be accepted upstream. @RabiaSajjad is this one worth getting translated?

**Comment by JVickery-TBS** [comment]
@wardi does not look like there are any fuzzies in the updated POs. And no missing french translations either.

**Review by wardi — APPROVED** [review]
ok this just fills in the pot file and updates some comments

**Comment by JVickery-TBS** [comment]
Yeah according to git commits, Rabia already got all of the French translations in last year for this extension

**Pull request merged**
